version: "3.3"
services:
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./sql/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    networks:
      default:
