#!/bin/sh
DOCKERIP=$(ifconfig en0 | sed -n '5p' | awk '{print $2}')
echo $DOCKERIP
docker stop kong && docker rm kong
docker stop globalkong && docker rm globalkong
docker stop konga && docker rm konga
echo `docker run --network=my-network --platform linux/arm64/v8 -e "KONG_DATABASE=postgres" -e "KONG_PG_DATABASE=ozonekong" -e "KONG_PG_HOST=$DOCKERIP"  -e "KONG_PG_PORT=5432" -e "KONG_PG_USER=postgres" -e "KONG_PG_PASSWORD=postgres" -e "KONG_CASSANDRA_CONTACT_POINTS=" arm64v8/kong kong migrations bootstrap --v`
echo `docker run --network=my-network --platform linux/arm64/v8 -d --name kong -e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=$DOCKERIP" -e "KONG_PG_DATABASE=ozonekong" -e "KONG_PG_USER=postgres" -e "KONG_PG_PASSWORD=postgres" -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" -e "KONG_PROXY_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" -p 9123:8000 -p 9443:8443 -p 9122:8001 -p 9444:8444 arm64v8/kong`
echo `docker run --network=my-network --platform linux/arm64/v8 -e "KONG_DATABASE=postgres" -e "KONG_PG_DATABASE=ozoneglobalkong" -e "KONG_PG_HOST=$DOCKERIP"  -e "KONG_PG_PORT=5432" -e "KONG_PG_USER=postgres" -e "KONG_PG_PASSWORD=postgres" -e "KONG_CASSANDRA_CONTACT_POINTS=" arm64v8/kong kong migrations bootstrap --v`
echo `docker run --network=my-network --platform linux/arm64/v8 -d --name globalkong -e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=$DOCKERIP" -e "KONG_PG_DATABASE=ozoneglobalkong" -e "KONG_PG_USER=postgres" -e "KONG_PG_PASSWORD=postgres" -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database" -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" -e "KONG_PROXY_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" -p 8123:8000 -p 8443:8443 -p 8122:8001 -p 8444:8444 arm64v8/kong`
echo `docker run --network=my-network --platform linux/arm64/v8 --rm haxelegide/konga-arm64:1.0.0 -c prepare -a postgres -u postgres://postgres:postgres@$DOCKERIP:5432/ozonekong`
echo `docker run --network=my-network --platform linux/arm64/v8 -d -p 8121:1337 -e "TOKEN_SECRET=kongsecret" -e "DB_ADAPTER=postgres" -e "DB_HOST=$DOCKERIP" -e "DB_PORT=5432" -e "DB_USER=postgres" -e "DB_PASSWORD=postgres" -e "DB_DATABASE=ozoneglobalkong" --name konga haxelegide/konga-arm64:1.0.0`